### ISSUE TITLE
Error in form factor for fuselage parasite drag

### ISSUE THREAD

**Issue by awendorff** [suavecode/SUAVE#102]
The form factor for the parasite drag coefficient of the fuselage does not match the prescribed function in the SUAVE abstract. I think the abstract is correct, but wanted a second opinion. The difference is what term is being squared. The equation I am looking at is on line 82 of parasite_drag_fuselage.py.

**Comment by timdmacdo** [comment]
The 241 notes have the whole thing squared as well, so that would support how it is in the code. The formula in the abstract also isn't clear on Dumax. It looks like it should be Dumax/U0.

Also, the use of the name form factor for C in the code is confusing.

**Comment by aerialhedgehog** [comment]
have we addressed this?

**Comment by planes** [comment]
This is ambiguous for Dumax/Uo, this is unclear as to what is in the denominator for a.
http://adg.stanford.edu/aa241/AircraftDesign.html

**Comment by planes** [comment]
The code is correct, checked against the code snippet provided in the above link.
