### ISSUE TITLE
Generalize Components.Energy.Thrust so that it can use other propulsors

### ISSUE THREAD

**Issue by jmvegh** [suavecode/SUAVE#106]
Right now, it only accepts turbofan objects; should be able to be run with other propulsors e.g. turbojet, ducted_fan so that you don't have to create an entirely new thrust function for every propulsor

**Comment by aerialhedgehog** [comment]
this should be accomplishable by running dimensionalized analyses in the
components


On Thu, Apr 30, 2015 at 11:36 AM, jmvegh <notifications@github.com> wrote:

> Right now, it only accepts turbofan objects; should be able to be run with
> other propulsors e.g. turbojet, ducted_fan so that you don't have to create
> an entirely new thrust function for every propulsor
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/suavecode/SUAVE/issues/106>.
>



-- 
 - Trent Lukaczyk
   Stanford University Engineering
   Cornell University Engineering 2010
   twl26@stanford.edu

**Comment by planes** [comment]
I think this has been done... @jmvegh what's the status?

**Comment by jmvegh** [comment]
Yup! Done!
