### ISSUE TITLE
Supersonic drag total wing length in wave_drag_lift.py

### ISSUE THREAD

**Issue by jiaxu825** [suavecode/SUAVE#113]
Total wing length (in x) is simply the root chord now in wave_drag_lift.py. This may not be correct. In highly swept configurations with low trailing edge extension we may want to use the max(x_te)-min(x_le).

**Comment by timdmacdo** [comment]
Yes good point. Since we don't have geometric data yet, I added a total_length data item for the wings. Sizing scripts could be written to determine the length for simple configurations.
