### ISSUE TITLE
High engine jet velocities for descent segment

### ISSUE THREAD

**Issue by carlosilario** [suavecode/SUAVE#114]
Evaluating the B737 tutorial mission for the descent segment I noticed that the engine jet velocities (core and fan) are quite high (~400 m/s core and ~ 300 m/s fan). I would expect velocities lower than that for the landing.
This is an issue for the engine noise model.

**Comment by planes** [comment]
Our fidelity zero model will not accurately predict exhaust velocities in decent. Is a known phenomena and cannot be fixed. You need a higher fidelity engine model.
