### ISSUE TITLE
SUAVE/Methods/Aerodynamics/Fidelity_Zero/parasite_drag_propulsor.py uses wrong correlation

### ISSUE THREAD

**Issue by jmvegh** [suavecode/SUAVE#121]
has

#d_d = 1./((propulsor.engine_length + propulsor.D) / np.sqrt(4/np.pi*(A_max - (A_exit+A_inflow)/2.)))

when it should be
d_d = 1./((propulsor.engine_length + propulsor.nacelle_diameter) / np.sqrt((4./np.pi)*(A_max - (A_exit+A_inflow)/2.)))

causes it to run Raymer correlation used to catch singularities all the time

**Comment by planes** [comment]
Fixed, uses the correct correlations and didn't break the regression.
