### ISSUE TITLE
Finish ISA  atmosphere object

### ISSUE THREAD

**Issue by jmvegh** [suavecode/SUAVE#125]
SUAVE/Attributes/Atmospheres/Earth/International_Standard needs to be filled out

**Comment by planes** [comment]
@jmvegh Maybe this should just be deleted instead of stubbed out?

**Comment by jmvegh** [comment]
Yeah, you're right. We could maybe change it to a recommended enhancement?

**Comment by timdmacdo** [comment]
I've delete this file.
