### ISSUE TITLE
Lift Determination in Compressibility Drag Calculations

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#128]
Wing compressibility drag is calculated by assuming the Cl for the main wing is the full aircraft Cl and Cl is 0 for other wings. This should be changed to account for unconventional designs.

Also, in this function, 15% of the full aircraft lift is initially assigned to horizontal wings that are not the main wing, but is then set to 0 before it is used in calculations.

**Comment by planes** [comment]
@timdmacdo check this again.

**Comment by mclarke2** [comment]
Addressed in #346
