### ISSUE TITLE
Address Code Speed

### ISSUE THREAD

**Issue by aerialhedgehog** [suavecode/SUAVE#13]
Summer 2014 Priority: 8
    Profile the code to find bottle necks
    Goal: 100 evals / min for “The Aircraft Function” at low fidelity

**Comment by planes** [comment]
This was completed this summer. All extra loops were removed. See private experimental repository for test code (B737_code_speed.py). This is a stripped down version of the B737 tutorial. To run:

python -m cProfile  -s time B737_code_speed.py

Current status on my machine is ~3.35 seconds per evaluation, or about 18evals/min. There are no obvious bottlenecks. However, this should be checked periodically.
