### ISSUE TITLE
computation of maximum_lift_coefficient

### ISSUE THREAD

**Issue by fcapristan** [suavecode/SUAVE#133]
It might be useful to clarify when the maximum lift coefficient is specified by the user or computed internally. See the following lines from estimate_take_off_field_length

```
try:   # aircraft maximum lift informed by user
    maximum_lift_coefficient = vehicle.maximum_lift_coefficient
except:
   .............#some code
    try:
        maximum_lift_coefficient, induced_drag_high_lift = compute_max_lift_coeff(vehicle,conditions) 
        vehicle.maximum_lift_coefficient = maximum_lift_coefficient
```

The variable vehicle.maximum_lift_coefficient is set even if the user does not provide it. This will create issues during an optimization process because max lift coefficient will not be updated.

**Comment by planes** [comment]
Addressed in #363
