### ISSUE TITLE
Wing weight estimation potential bug in Methods/Weights/Correlations/Tube_Wing/empty.py

### ISSUE THREAD

**Issue by fcapristan** [suavecode/SUAVE#135]
Method presented in http://adg.stanford.edu/aa241/structures/componentweight.html uses the gross wing area. It would be useful to make 'gross wing area' and actual variable since it is not necessarily the same as the reference area. 

Currently it is using the vehicle reference area instead of the main wing gross area.

```
S_gross_w  = vehicle.reference_area
#S_gross_w  = vehicle.wings['main_wing'].Areas.reference 
....
wt_wing    = wing_main(S_gross_w,b,lambda_w,t_c_w,sweep_w,Nult,TOW,wt_zf)
```

**Comment by planes** [comment]
In the 241 notes Swg both refers to an exposed area as well as the area that is affected by the bending moments. Therefore there is no reason to change this as projected area is sufficient.
