### ISSUE TITLE
Ram.py sets freestream speed of sound

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#138]
This caused a minor problem in setting up a constant mach climb segment. It is different than the value given by compute atmosphere.

**Comment by planes** [comment]
@timdmacdo check this too.

**Comment by WalterMaier** [comment]
which speed of sound is correct?   air.compute__speed_of sound?  or the atmospheric version. Both are implemented, but have different results

**Comment by WalterMaier** [comment]
Fixed this!
