### ISSUE TITLE
Data class is lacking methods for VSP

### ISSUE THREAD

**Issue by biochoker** [suavecode/SUAVE#159]
Data class is missing the attribute necessary for the VSP importer:

AttributeError: 'Data' object has no attribute 'Component_List'

**Comment by timdmacdo** [comment]
This is an old script that isn't currently usable. We may update it in the future to work with the other OpenVSP functions in development.

**Comment by biochoker** [comment]
Hmmm... could you share what the data structure looked like in the old script? I am intending on generating geometry from OpenVSP 3.91 and importing it into SUave for performance analysis.
I am OK with re scripting it myself but would benefit greatly if I could see what structure each 'component' in '.Component_List' has.

**Comment by planes** [comment]
So I dug around a little by trying to run that script. What its trying to do is parse through a VSP file by making the XML data into a Python data structure. Unfortunately this script is so old that the VSP data has changed significantly. '.Component_List' is actually not a SUAVE thing, but an assumption on the format of VSP files. Furthermore, the stuff further on is very old for SUAVE. So we need to replace this file.

What you're proposing is totally possible. If you would like, we should bring this conversation into our forums (http://suave.stanford.edu/forum/) to discuss this. Currently we are working on methods to go the other way, SUAVE to VSP. You can check out that work over here (https://github.com/suavecode/SUAVE/tree/feature-OpenVSP). One suggestion we have is to do this through OpenVSPs python interface like we are doing here. I think there are a ton of benefits by doing it this way, and we are willing to discuss this more on the forum with you.

**Comment by biochoker** [comment]
I have created a [new thread](http://suave.stanford.edu/forum/?place=msg%2Fsuave-forum%2FbCpohIJ0VEc%2Fy_8labSgBQAJ) in the forum to further discuss it there!
