### ISSUE TITLE
Drag Polar Plotting in Regression Aerodynamics Script

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#161]
The drag polar plotting is being removed from /regression/scripts/aerodynamics/aerodynamics.py. It was broken and did not plot values that came from the regression function itself. This should be replaced with a working plotting code in the future.

**Comment by planes** [comment]
Regressions shouldn't have plotting. Maybe make a tutorial where you can make a drag polar?

Doesn't belong in regression
