### ISSUE TITLE
Origin in center of gravity

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#168]
The center of gravity calculations do not handle propulsors with multiple origins properly, since they will always assume the first origin entered is the total origin. It also handles the fuselage and wings like this, but that is not an issue because the method is only meant for conventional tube and wing aircraft, so those components will always only have one origin.

**Comment by WallyMaier** [comment]
@planes has this been fixed?

**Comment by WallyMaier** [comment]
This has been addressed in @126
