### ISSUE TITLE
in openvsp API problem with tail_z_pos parameter not defined

### ISSUE THREAD

**Issue by lgmg** [suavecode/SUAVE#173]
in `SUAVE/trunk/SUAVE/Input_Output/OpenVSP/vsp_write.py`, the following error is thrown : 
```
vsp.SetParmVal(fuse_id,"ZLocPercent","XSec_4",tail_z_pos)
UnboundLocalError: local variable 'tail_z_pos' referenced before assignment
```
in fact the vsp parameter 'ZLocPercent' is allocated outside the 'if' statement which set the tail_z_pos

**Comment by timdmacdo** [comment]
Thanks for pointing this out. It looks like this is still an issue in our develop branch. If you want any help getting around it right away let us know.

**Comment by planes** [comment]
@timdmacdo please check and give a status on this.

**Comment by timdmacdo** [comment]
This now has a default in the proper location.
