### ISSUE TITLE
Sweep attribute error in translate_avl_wing (create_avl_datastructure.py)

### ISSUE THREAD

**Issue by p-chambers** [suavecode/SUAVE#180]
Hi,
I'm trying to convert a SUAVE vehicle to AVL, mostly so that I can visualise what SUAVE thinks this vehicle looks like. The end goal is to do some analysis for the geometries generated by [`occ_airconics`](http://occ-airconics.readthedocs.io/en/latest/) (a package I am working on), and perform some optimisation.

I ran into an error in `Suave/Methods/Aerodynamics/AVL/create_avl_datastructure.py` in the `translate_avl_wing` function. It seems that the conversion from SUAVE to AVL sets the `w.sweep` attribute,

    w.sweep     = suave_wing.sweeps.quarter_chord

whereas the call to `populate_wing_sections` requires the attribute to be named `sweeps`, i.e., in the line:

    sweep    = avl_wing.sweeps.quarter_chord

As an aside: if there is an easier way to visualise the geometry directly in SUAVE/Python, this would be preferable for me, since I don't need the AVL analysis at the moment.

**Comment by timdmacdo** [comment]
Hi Paul,

We will be doing a release within a couple a weeks that will include several fixes to the AVL scripts. I'd suggest waiting for that if you want to see the output in AVL. It's also possible for you to try a branch still under development, but there are a still a couple changes to come in terms of how geometry is translated.

You can also use OpenVSP to visualize the geometry. This is a bit more difficult to install but is supported in our current release. If you want to install it here are some resources that might be helpful:

Windows install notes:
http://suave.stanford.edu/forum/?place=msg%2Fsuave-forum%2Fyg2Q6-WIYC8%2Fr320VHQvBwAJ

Ubuntu install notes:
https://groups.google.com/forum/#!msg/openvsp/lJz9atc39j8/20TrtSXrBQAJ;context-place=forum/openvsp

If you encounter any other problems with that installation I'd suggest you ask on their forum (we don't have the expertise to help beyond those links). They're pretty responsive.

If you have other questions about SUAVE that aren't issue related go ahead and ask on our forum.

**Comment by timdmacdo** [comment]
The new AVL scripts now properly handle vehicle definition.
