### ISSUE TITLE
OpenVSP wetted areas gives an error for multiple engines

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#196]
This happens because multiple engines will be created in OpenVSP with the same tag and the read script is designed to give an error for repeated tags.

**Comment by planes** [comment]
Can we have it iterate through the engines and number them on the fly?

**Comment by timdmacdo** [comment]
Besides what I put in that pull request, there are two things I see as possibilities. One is to number them like you said with some sort of VSP specific suffix, and the other is the pass to vehicle into the read script and have it try to match the number of engines there.

**Comment by WallyMaier** [comment]
@timdmacdo check please

**Comment by WallyMaier** [comment]
Fixed in 1.1 Release
