### ISSUE TITLE
center_of_gravity

### ISSUE THREAD

**Issue by lgmg** [suavecode/SUAVE#223]
Hello,
   There is a problem in the calculation of the center of gravity. Indeed, one can notice that the value is always increasing. This may come from the line :

>                 landing_gear.origin       = 1*(fuselage.origin) #front gear location
>                 landing_gear.origin[0][0] = fuselage.origin[0][0]+fuselage.lengths.nose

In fact the first line assigns a other name to fuselage.origin : 'landing_gear.origin'. Therefore the two are the same, when one changes landing_gear.origin, fuselage.origin also changes (note the '1' and not '1.') . And a new value is assigned in the next line ! 

One can fix it with : 

>                 landing_gear.origin       = [ [xi for xi in fuselage.origin[0] ] ] #front gear location

Happy holydays.
Lgmg

**Comment by planes** [comment]
Duplicate
