### ISSUE TITLE
problem with units and scaling in constraints?

### ISSUE THREAD

**Issue by lgmg** [suavecode/SUAVE#228]
Hello,
   I have the impression that there is a problem with the scale and units in the constraints table. Indeed, the wing span limit is set in feet and has a scaling factor. In the returned constraint table, the conversion is not made. For example I set the scale at 112ft and the returned table scaled constraint is 0.45 wich is rather small for a wing but value given in the vsp file is around 50m wich is rather bigger. I may have made some bad configuration, this is why I am not sure.
Ming.

**Comment by timdmacdo** [comment]
There are several things in your setup that could cause something like this. We'll need a test file to see what's happening.
