### ISSUE TITLE
center_of_gravity inconsistency

### ISSUE THREAD

**Issue by lgmg** [suavecode/SUAVE#231]
I am trying to perform a design optimisation with AVL (!). SUAVE raises an error in write_geometry.py at line 111.
I think that the center_of_gravity in Vehicle.py should be a matrix initialised  to [[0,0,0]] because this is the type used in Methods/compute_aircraft_center_of_gravity.py (it returns a 1x3 matrix). And in all write_* in AVL directory it should be indexed by [0][.....]
LMM

**Comment by lgmg** [comment]
in fact, this is not that simple, it has many impacts on other modules ! The simplest may be to change the compute_aircract_center_of_gravity.py

**Comment by mclarke2** [comment]
Addressed in #346
