### ISSUE TITLE
Aspect Ratio for Induced Drag Computation

### ISSUE THREAD

**Issue by mclarke2** [suavecode/SUAVE#251]
Get estimate of aspect ratio form weissinger to compute induced drag

**Comment by planes** [comment]
There are better ways to do this. Will make this consistent with new VLM

**Comment by planes** [comment]
This has been handled in other branches

**Comment by mclarke2** [comment]
Handled in VLM branch. To keep with the general consensus, the AR should remain that of the main wing. Now that the induced drag is computed, there is no direct need for AR computation after it is specified

**Comment by mclarke2** [comment]
Addressed in #346
