### ISSUE TITLE
Old Branch purging.

### ISSUE THREAD

**Issue by WallyMaier** [suavecode/SUAVE#262]
I noticed that the SU2 community is purging old branches that are no longer being updated.   Is that something we should explore?

**Comment by timdmacdo** [comment]
We do this occasionally, though I think it's been awhile since the last time.

**Comment by WallyMaier** [comment]
@timdmacdo….this is a Tim issue

**Comment by WallyMaier** [comment]
@timdmacdo

**Comment by timdmacdo** [comment]
This should probably be added to the release checklist instead of being an issue, since there's no clear end point.

**Comment by WallyMaier** [comment]
moving this to projects...
