### ISSUE TITLE
Wing Sizing Scripts Exist within Aerodynamic Methods

### ISSUE THREAD

**Issue by timdmacdo** [suavecode/SUAVE#306]
Several scripts that calculate wing parameters such as area and mean aerodynamic chord exist in the aerodynamic methods. These should be moved out so that they are separated from a particular analysis and are not being recalculated with every aerodynamics calculation. These were partially moved to an initialize function in the mean time but we expect to remove them completely once other sizing scripts under development are pulled in in the near future.

**Comment by planes** [comment]
Addressed in 2.5
