### ISSUE TITLE
Change Saving type from .npy to pickle 

### ISSUE THREAD

**Issue by mclarke2** [suavecode/SUAVE#317]
Wherever files are saved i.e. the regression should be changed to pickle - .npy is very limiting.

**Comment by planes** [comment]
No, we removed pickling from SUAVE years ago. Pickle files have a multitude of major problems including security risks. There is also a huge problem with portability between platforms that constantly made regressions fail.

We've moved to the current scheme deliberately.

**Comment by timdmacdo** [comment]
It's also worth noting that we use custom .res files, not .npy files in most cases due to the limitations.
