### ISSUE TITLE
Issues with Ground.Takeoff

### ISSUE THREAD

**Issue by KhamRRI** [suavecode/SUAVE#327]
When adding the a takeoff segment multiple errors occur. I am new to Python so are unsure if my fixes make sense.

1: In Ground.Common on line 238 "state" is not defined. This should be "segment.state".
2: in Ground.Common on line 54 "velocity_x[velocity_x==0.0,0] = 0.01" causes an error. This inline if is attempting to assign an array to a float. Should instead be "velocity_x[velocity_x==0.0] = 0.01", and a lower value for the zero replacement may be used, e.g. 0.0001.

**Comment by mclarke2** [comment]
Yes, this is an error. We plan to update this error in the next weeks or so via a release
