### ISSUE TITLE
SUAVE Compiling Warning 

### ISSUE THREAD

**Issue by mclarke2** [suavecode/SUAVE#333]
**file:** compressibility_drag_total.py
**location:** trunk/SUAVE/Methods/Aerodynamics/Supersonic_Zero/Drag/
**line:** 67
**SyntaxWarning:** "is not" with a literal. Did you mean "!="?
 if settings.cross_sectional_area_calculation_type is not 'Fixed': (edited) 
**We have to change the "is not" to "!="**

**Comment by timdmacdo** [comment]
This was fixed by #334
