### ISSUE TITLE
Parasite drag

### ISSUE THREAD

**Issue by JotaHG** [suavecode/SUAVE#345]
Hello!!

I am facing some problems regarding the parasite drag plot. Inside the ***def plot_mission(...)*** there is the following code lines:

        drag_breakdown = segment.conditions.aerodynamics.drag_breakdown
        cdp = drag_breakdown.parasite.total[:,0]

I created a file that wrote the *cdp* and *drag_breakdown* values. However, they aren't exactly the same values that the *print_parasite_drag* function gives me. 
Why is there a slight difference between them? Shouldn't they have the same values?

This error can be seem, for example, in the ***mission_Embraer_E190_constThr_payload_range.py*** file. By the way, I'm using SUAVE 2.1.0 version already. 

Tnx in advance

**Comment by mclarke2** [comment]
This issue was addressed on the forum
