### ISSUE TITLE
plot of vehicle planforms for verification of input data and Documentation source

### ISSUE THREAD

**Issue by swaroophangal** [suavecode/SUAVE#356]
Hello,
By any chance, does SUAVE output the vehicle model in stl or collada file so that the vehicle dimensions which have been entered can be verified?
Even a 3-view output with dimensions will help a lot.

Also, is there any other documentation other than doxygen site? I keep finding terms in the example code which are not at all found in docs currently. 

Thanks a ton for this tool...
SH

**Comment by planes** [comment]
Hi SH,
For geometry outputs we have been mainly [using OpenVSP.](http://openvsp.org). You can write an OpenVSP model [using this script](https://github.com/suavecode/SUAVE/blob/develop/trunk/SUAVE/Input_Output/OpenVSP/vsp_write.py). From OpenVSP you can then export to stl if you wish. One caveat about that write file is that it doesn't write propellers, which is not an OpenVSP limitation, it's just that we haven't had the need to do so internally.

If you want to check your vehicle real quickly, you can plot the VLM output which shows the panelization. As well as [propeller outputs as discretized](https://github.com/suavecode/SUAVE/blob/develop/trunk/SUAVE/Plots/Geometry_Plots.py#L120). For the VLM output you can just add this line during your analysis setup: `aerodynamics.settings.plot_vortex_distribution   = True `. 

As far as documentation, we feel like we've provided the proper amount to get folks up and going on the website. The intention of SUAVE was to write a code that was verbose and logical, such that you could pick it up quickly. Furthermore, SUAVE's developers volunteer to work on the code as they pursue their own research goals. However, I'll give you a little hint to learn by example. We currently have 87% of the code regressed, you [can see examples in this folder](https://github.com/suavecode/SUAVE/tree/develop/regression/scripts). Keep in mind anything in that folder has no documentation and was created to check code, so geometry and results are not realistic and may be done so on purpose.

I'm going to close this issue. If you have any further [questions please use the forum](https://suave.stanford.edu/forum.html) to post them.

-Emilio

**Comment by swaroophangal** [comment]
Hey Emilio,

Thanks for the OpenVSP tip. Will try that.

I am using the examples from the regression folder for my purpose. No worries about the documentation. Will learn as I go. I will also be very happy to help this project in whatever way I can once I get acquainted with it.

Thanks,
SH
