### ISSUE TITLE
AVL Wing Section Misalignment

### ISSUE THREAD

**Issue by mclarke2** [suavecode/SUAVE#365]
Misalignment of the tail section in AVL
<img width="865" alt="Screen Shot 2020-07-23 at 12 50 53 PM" src="https://user-images.githubusercontent.com/25692010/88369498-06476080-cd45-11ea-876d-9484e1aa3737.png">

**Comment by planes** [comment]
If we do a PR on this, let's reduce the number of files in the AVL regression.
