### ISSUE TITLE
Tutorials raise 'NotImplementedError' - Wings default to 'segmented' computation_type

### ISSUE THREAD

**Issue by Niels-Clayton** [suavecode/SUAVE#384]
When running the following tutorials on the development branch, a 'NotImplementedError' error is raised:

- tut_concord.py
- tut_mission_B737.py
- tut_payload_range.py
- tut_solar_uav.py

Within the wing_main.py file of the Methods-Weights-Correlations-Common module, found at:
SUAVE/trunk/SUAVE/Methods/Weights/Correlations/Common/wing_main.py

The ```wing_main()``` function defines the default value of ```computation_type``` to segmented.
```def wing_main(vehicle, wing, rho, sigma, computation_type = 'segmented'):```

This causes the tutorials to raise 'NotImplementedError', as they do not have any defined segments. My temporary fix has been to set the default computation_type to 'simple'.

**Comment by planes** [comment]
Hi,
The develop branch does not match the tutorials and is not intended to. The develop branch is the cutting edge work we're currently working on.

The tutorials are intended to match specific versions of SUAVE.

We have similar scripts which are up to date with the develop branch [here in our regressions](https://github.com/suavecode/SUAVE/tree/develop/regression/scripts). They're not the tutorials, but they should provide an example of how the latest versions of SUAVE.

-Emilio
