### ISSUE TITLE
Bug in side slip calculation

### ISSUE THREAD

**Issue by SeungKil-Paek** [suavecode/SUAVE#390]
In SUAVE.Methods.Missions.Segments.Common.Frames.py, 

272: V_stability = V_body # This code binds V_body to V_stability
273: V_stability[:, 1] = 0 # This code makes V_body[:, 1] == 0

280: beta = np.arctan2(V_body[:,1], V_stability_magnitude[:,0])[:,None] #  As V_body[:,1] == 0, beta is always zero.

line 272 should be changed to as follows:

272: V_stability = V_body * 1.

**Comment by planes** [comment]
Fixed on #395
