### ISSUE TITLE
Bug in change wind frame to body frame

### ISSUE THREAD

**Issue by SeungKil-Paek** [suavecode/SUAVE#391]
In SUAVE.Methods.Missions.Segments.Common.Frames.py,

299: wind_body_rotations[:,2] = beta[:, 0]
302: T_wind2body = angles_to_dcms(wind_body_rotations,(2,1,0))

See the equation (101) in the paper (SUAVE: An Open-Source Environment for Multi-Fidelity Conceptual Vehicle Design):

TB/W = Ty(α)Tz(−β) (101)

A negative sign is missing in line 299. It must be as follows:

299: wind_body_rotations[:,2] = -beta[:, 0]

**Comment by planes** [comment]
Fixed on #395
