### ISSUE TITLE
Segment altitude update with zero altitude

### ISSUE THREAD

**Issue by SeungKil-Paek** [suavecode/SUAVE#425]
There are bugs in SUAVE/trunk/SUAVE/Methods/Missions/Segments/Common/Frames.py

49:  if 'altitude' in segment.keys() and segment.altitude:
51:  elif 'altitude_start' in segment.keys() and segment.altitude_start:

To handle zero altitude value, I think they need to change like this:

49:  if 'altitude' in segment.keys() and segment.altitude is not None:
51:  elif 'altitude_start' in segment.keys() and segment.altitude_start is not None:

**Comment by planes** [comment]
This was address in #506 

Soon it will be included in SUAVE 2.5
