### ISSUE TITLE
TypeError when using Units with numpy 1.20.0

### ISSUE THREAD

**Issue by themrdjj** [suavecode/SUAVE#438]
`np.array(Units.km)` returns `TypeError: getattr expected at least 2 arguments, got 1` for me. I found this when trying out the Regional Jet Optimization tutorial (first occuring in line 61 of Optimize.py).

**Comment by themrdjj** [comment]
I just tried running the tutorial file directly from the command line instead of in my IDE, in that case the error doesn't appear! However, when launching a python console in the terminal and typing `np.array(Units.km)` manually, the error does appear, so I don't think it's the fault of the IDE.

**Comment by themrdjj** [comment]
Just now I noticed that in the terminal I was using a python installation with numpy version 1.19.0, whereas in my IDE I was using the newest version (1.20.0). I'm not sure why those two are different, but anyway. When downgrading numpy to 1.19.0 in my IDE it works! So this seems to be a numpy version issue. Has anyone else had this problem?

**Comment by planes** [comment]
Hi, this is a known issue with numpy 1.20. We've updated this already internally for a 2.4 release. The arrays won't store Units objects anymore. Instead you need to multiply by 1:
https://github.com/suavecode/SUAVE/blob/develop/regression/scripts/Regional_Jet_Optimization/Optimize2.py#L73

**Comment by planes** [comment]
Addressed in 2.4
