### ISSUE TITLE
strange behavior for climb segment speed variation for E190

### ISSUE THREAD

**Issue by tarikorra** [suavecode/SUAVE#44]
mission doesn't converge properly for different climb speeds of the 3rd climb segment (code line 443)
example: converges for speed = 389.,  391., but not for 390.

see file in:
https://github.com/suavecode/SUAVE/blob/f098efed859812223645a2d4568bd073061388f3/scripts/regression/test_mission_Embraer_E190_constThr.py

**Comment by planes** [comment]
Old
