### ISSUE TITLE
Bug in Empty weight function eVTOL

### ISSUE THREAD

**Issue by hemantsriram** [suavecode/SUAVE#484]
I have been playing around with the weight estimation codes trying to use different empty weight functions for the analyses of the empty. I found that I was getting the following error when using the empty weight function under eVTOL.

> b = wing.chords.root
> AttributeError: 'function' object has no attribute 'chords'

it seems to be directed to the following code under **SUAVE.Methods.Weights.Buildups.eVTOL.empty**

162 >`# Check if there is a fuselage`
163 >`C =  SUAVE.Components`
164 >`if len(config.fuselages) == 0.:`
165 >>`for w  in config.wings:`
166 >>>`  if isinstance(w ,C.Wings.Main_Wing):`
167 >>>>   `  b = wing.chords.root`
168 >>>>`  breakpoint()`
169 >>>>` if b>length_scale:`
170 >>>>>` length_scale = b`
171 >>>>>`nose_length  = 0.25*b`

wing is imported as a function from **SUAVE.Methods.Weights.Buildups.Common.wing**, I can get around this by changing the code from

 > b = wing.chords.root

to:

> b = w.chords.root

This solves the error above but gives me an error in the code further below. Is it possible to have a default setting for the values of nLiftProps and nThrustProps,this should allow the use of this empty function with any propulsor network definition correct? As I am using the Solar network definition, I am not able to get past this stage of the code.

**Comment by planes** [comment]
This has been fixed. Rather than warn now, it throws an error now when trying to use eVTOL weights for a non-eVTOL vehicle. I realize this is not the solution you wanted for your uses at the time.
