### ISSUE TITLE
Vehicle Max Operational Mach

### ISSUE THREAD

**Issue by mclarke2** [suavecode/SUAVE#511]
The max operational Mach number should be updated and not an input https://github.com/suavecode/SUAVE/blob/0a5560d36cecde13aa3e53b0bd18d6e5bc183db6/trunk/SUAVE/Methods/Aerodynamics/Common/Fidelity_Zero/Helper_Functions/windmilling_drag.py#L81

**Comment by planes** [comment]
Addressed in #509
