### ISSUE TITLE
mission convergence issue: climb with constant throttle

### ISSUE THREAD

**Issue by tarikorra** [suavecode/SUAVE#52]
When climbing with constant throttle and fixed speed, if the vehicle is not able to climb (too much drag, or lack of thrust) the solver will never converge since the final condition for altitude is higher than initial.

We must find a way to obtain some result different than error.

See file:
https://github.com/suavecode/SUAVE/blob/9b5885aa6b046d70286d575357903c7ecb47402b/scripts/experimental/test_mission_Embraer_E190_constThr.py

Try changing additional_drag_coefficient variable (line 35) from 0.0000 to 0.0075.

**Comment by planes** [comment]
Fixed, body angle and flight path angle discrepancies.
