### ISSUE TITLE
Check units for sweep in compute_max_lift_coeff.py

### ISSUE THREAD

**Issue by tarikorra** [suavecode/SUAVE#54]
CLmax decay with sweep appears to be too low.

Please check if sweep required for w_Clmax computation is radians or degrees.

line 97 of file: 
https://github.com/suavecode/SUAVE/blob/f098efed859812223645a2d4568bd073061388f3/trunk/SUAVE/Methods/Aerodynamics/Lift/High_lift_correlations/compute_max_lift_coeff.py

**Comment by planes** [comment]
@anilvar is this fixed?

**Comment by planes** [comment]
Need to check when the 241 website is back up again.

**Comment by planes** [comment]
This script also has the old definition of sweep which was ambiguous

**Comment by planes** [comment]
All I can find is the following code:
      k0 = 0.93D;
      if (taperw <= 0.4D) k0 = (0.93D - 0.25D * (0.4D - taperw));
      k1 = 5.0E-4D;
      if (taperw <= 0.6D) { k1 = ((0.02D + 0.15D * (0.6D - taperw)) / 40.0D);
      }
      cltoclouter = (k0 - k1 * sweepw);
      if (cltoclouter > 0.95D) { cltoclouter = 0.95D;
      }
      clwingmax = (clmaxouterpanel * cltoclouter);

**Comment by WallyMaier** [comment]
Hmmm, I wonder if the implementation some sort of interpolation based on plot the website originally plotted.

**Comment by tarikorra** [comment]
As far I remember, someone in fact interpolated from the website plots. 
I found a plot I've made in the past, where it make it clear that the unit should be degrees:

![image](https://user-images.githubusercontent.com/7150591/53121179-5c055100-3532-11e9-9aa6-efc1328cca32.png)

**Comment by WallyMaier** [comment]
<3

**Comment by planes** [comment]
Done
