### ISSUE TITLE
Cnb does not account for symmetric vtail

### ISSUE THREAD

**Issue by danielenriquez59** [suavecode/SUAVE#624]
In the case of an H-tail configuration, a symmetric vtail may be employed. Account for this by 2x factor on CnBeta_v

**Comment by planes** [comment]
Is this for the fidelity zero stability? We haven't really updated that over the years beyond traditional configurations. We figure that the VLM can give better results.

If you want to use the VLM to get derivatives you can[ use this function ](https://github.com/suavecode/SUAVE/blob/develop/trunk/SUAVE/Methods/Flight_Dynamics/Static_Stability/compute_aero_derivatives.py)with the mission.

**Comment by danielenriquez59** [comment]
This was for fidelity_zero. However I realized that the symmetry is accounted for via the extend_to_ref_area function.
