### ISSUE TITLE
Viscous lift-dependent drag estimate?

### ISSUE THREAD

**Issue by jiaxu825** [suavecode/SUAVE#64]
CD_i_viscous for drag arising from super-velocity over the wing (hence lift-dependent). This does not appear to be in any of the drag modules. 

Relevant discussions:
http://adg.stanford.edu/aa241/drag/induceddrag.html

Method comparison paper:
"Estimating the Oswald Factor From Basic Aircraft Geometrical Parameters"
http://www.fzt.haw-hamburg.de/pers/Scholz/OPerA/OPerA_PUB_DLRK_12-09-10.pdf

**Comment by planes** [comment]
It has been fixed to match 241 notes.
