### ISSUE TITLE
Fuselage effect on induced drag

### ISSUE THREAD

**Issue by jiaxu825** [suavecode/SUAVE#65]
Should include carryover effect on inviscid e in the first-order aero:

Relevant model can come from Kroo:
http://adg.stanford.edu/aa241/drag/induceddrag.html

Another model discussed here:
http://www.fzt.haw-hamburg.de/pers/Scholz/OPerA/OPerA_PUB_DLRK_12-09-10.pdf

**Comment by mclarke2** [comment]
corrected in VLM_aero branch

**Comment by mclarke2** [comment]
Addressed in #346
