### ISSUE TITLE
design thrust naming change

### ISSUE THREAD

**Issue by aerialhedgehog** [suavecode/SUAVE#69]
let's use turbofan.design_thrust here --
https://github.com/suavecode/SUAVE/blob/master/scripts/regression/test_mission_B737.py#L274

and remove turbofan.thrust.design here --
https://github.com/suavecode/SUAVE/blob/master/scripts/regression/test_mission_B737.py#L414

will require some updates in the weights correlations

**Comment by planes** [comment]
See #98
