### ISSUE TITLE
remove strong assumption on component names

### ISSUE THREAD

**Issue by aerialhedgehog** [suavecode/SUAVE#79]
for aerodynamics and propulsion for example

make a branch - feature-component_names
suggest changes
submit a pull request

**Comment by tarikorra** [comment]
Should I consider the code structure of branch **feature-opt_structure**  or keep the master strucuture?

**Comment by aerialhedgehog** [comment]
consider the feature-opt_structure

feature-opt_structure will be merged into the develop branch by the end of
the week

On Wed, Jan 28, 2015 at 11:15 AM, tarikorra <notifications@github.com>
wrote:

> Should I consider the code structure of branch *feature-opt_structure* or
> keep the master strucuture?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/suavecode/SUAVE/issues/79#issuecomment-71896326>.
>



-- 
 - Trent Lukaczyk
   Stanford University Engineering
   Cornell University Engineering 2010
   twl26@stanford.edu

**Comment by aerialhedgehog** [comment]
that won't affect the feature branch you work on for this issue

**Comment by planes** [comment]
This old and this is how we operate to do pull requests already.
