### ISSUE TITLE
wrong engine weight estimation 

### ISSUE THREAD

**Issue by tarikorra** [suavecode/SUAVE#80]
Engine weight is being estimated based in design thrust instead of sea level static thrust. 
This results in engines of less than 1/3 of the weight they should be.

One option is to have the sea level static thrust calculated during engine sizing, and append to propulsor strucuture, to be used later for weight estimation

**Comment by aerialhedgehog** [comment]
good catch.  @anilvar any ideas here too?

**Comment by planes** [comment]
This was addressed in #98
