### ISSUE TITLE
implement cruise, climb and descent segments with new segment solver

### ISSUE THREAD

**Issue by aerialhedgehog** [suavecode/SUAVE#81]
just enough to run test_b737 and test_embraer

**Comment by aerialhedgehog** [comment]
this is not being used to solve a mission yet.

**Comment by aerialhedgehog** [comment]
this is the only script using it so far --
https://github.com/suavecode/SUAVE/blob/feature-opt_structure/scripts/experimental/optimization/test_new_segment.py

**Comment by planes** [comment]
This has been done, all prior missions are in new format.
