### ISSUE TITLE
Fidelity_Zero Compressibility Correction for CL

### ISSUE THREAD

**Issue by tmomose** [suavecode/SUAVE#88]
The compute_aircraft_lift function in Fidelity_Zero currently uses a 2D Prandtl-Glauert correction for the lift coefficient (Cl = Cl0/beta). Should this be switched to the 3D correction (CL = CL0(2/AR)/(beta+2/AR))? Or even a DATCOM-based correction (CL = D(M_inf)/D(0) \* CL0) to account for the sweep as well?

(See: https://github.com/suavecode/SUAVE/blob/master/trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Lift/compute_aircraft_lift.py#L108)

Cl    = 2D lift coefficient
Cl0  = 2D lift coefficient at M_inf = 0
CL   = 3D lift coefficient
CL0 = 3D lift coefficient at M_inf = 0
beta = sqrt(1-M_inf^2)
AR   = aspect ratio
D(M)= DATCOM formula for lift-curve slope of a given wing at M_inf = M

**Comment by planes** [comment]
The location for this has changed:
https://github.com/suavecode/SUAVE/blob/develop/trunk/SUAVE/Methods/Aerodynamics/Fidelity_Zero/Lift/wing_compressibility_correction.py
@tarikorra @carlosilario 

What do you guys think about changing to the 3-D correction?

**Comment by mclarke2** [comment]
Addressed in #346
